#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GoSteve.Resource", IsApplication=true)]

namespace GoSteve
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int alignment = 2131099658;
			
			// aapt resource value: 0x7f060046
			public const int barbarianBtn = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int bardBtn = 2131099719;
			
			// aapt resource value: 0x7f060023
			public const int blank1 = 2131099683;
			
			// aapt resource value: 0x7f060028
			public const int blank2 = 2131099688;
			
			// aapt resource value: 0x7f06002d
			public const int blank3 = 2131099693;
			
			// aapt resource value: 0x7f060032
			public const int blank4 = 2131099698;
			
			// aapt resource value: 0x7f060037
			public const int blank5 = 2131099703;
			
			// aapt resource value: 0x7f06003c
			public const int blank6 = 2131099708;
			
			// aapt resource value: 0x7f06000c
			public const int button1 = 2131099660;
			
			// aapt resource value: 0x7f06003e
			public const int chaMinus = 2131099710;
			
			// aapt resource value: 0x7f060040
			public const int chaPlus = 2131099712;
			
			// aapt resource value: 0x7f06003d
			public const int chaScore = 2131099709;
			
			// aapt resource value: 0x7f06003f
			public const int chaScoreNum = 2131099711;
			
			// aapt resource value: 0x7f060006
			public const int charBG = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int characterName = 2131099651;
			
			// aapt resource value: 0x7f060052
			public const int classDesc = 2131099730;
			
			// aapt resource value: 0x7f060004
			public const int classSelect = 2131099652;
			
			// aapt resource value: 0x7f060048
			public const int clericBtn = 2131099720;
			
			// aapt resource value: 0x7f06002f
			public const int conMinus = 2131099695;
			
			// aapt resource value: 0x7f060031
			public const int conPlus = 2131099697;
			
			// aapt resource value: 0x7f06002e
			public const int conScore = 2131099694;
			
			// aapt resource value: 0x7f060030
			public const int conScoreNum = 2131099696;
			
			// aapt resource value: 0x7f060044
			public const int continueBtn = 2131099716;
			
			// aapt resource value: 0x7f060020
			public const int continueButton = 2131099680;
			
			// aapt resource value: 0x7f06002a
			public const int dexMinus = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int dexPlus = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int dexScore = 2131099689;
			
			// aapt resource value: 0x7f06002b
			public const int dexScoreNum = 2131099691;
			
			// aapt resource value: 0x7f06000d
			public const int dmModeBtn = 2131099661;
			
			// aapt resource value: 0x7f060049
			public const int druidBtn = 2131099721;
			
			// aapt resource value: 0x7f060043
			public const int errMsg = 2131099715;
			
			// aapt resource value: 0x7f060001
			public const int exCharButton = 2131099649;
			
			// aapt resource value: 0x7f06004a
			public const int fighterBtn = 2131099722;
			
			// aapt resource value: 0x7f060010
			public const int instruction1 = 2131099664;
			
			// aapt resource value: 0x7f060021
			public const int instructionAb1 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int instructionAb2 = 2131099682;
			
			// aapt resource value: 0x7f06001b
			public const int instructionAlign = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int instructionBackground = 2131099677;
			
			// aapt resource value: 0x7f060045
			public const int instructionClass = 2131099717;
			
			// aapt resource value: 0x7f060014
			public const int instructionGender = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int instructionName = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int instructionRace = 2131099671;
			
			// aapt resource value: 0x7f060053
			public const int instructionSkills = 2131099731;
			
			// aapt resource value: 0x7f060019
			public const int instructionSubRace = 2131099673;
			
			// aapt resource value: 0x7f060034
			public const int intMinus = 2131099700;
			
			// aapt resource value: 0x7f060036
			public const int intPlus = 2131099702;
			
			// aapt resource value: 0x7f060033
			public const int intScore = 2131099699;
			
			// aapt resource value: 0x7f060035
			public const int intScoreNum = 2131099701;
			
			// aapt resource value: 0x7f060055
			public const int item0 = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int item1 = 2131099734;
			
			// aapt resource value: 0x7f06005f
			public const int item10 = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int item11 = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int item12 = 2131099745;
			
			// aapt resource value: 0x7f060057
			public const int item2 = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int item3 = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int item4 = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int item5 = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int item6 = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int item7 = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int item8 = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int item9 = 2131099742;
			
			// aapt resource value: 0x7f060005
			public const int level = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout1 = 2131099663;
			
			// aapt resource value: 0x7f06001f
			public const int missing1 = 2131099679;
			
			// aapt resource value: 0x7f06004b
			public const int monkBtn = 2131099723;
			
			// aapt resource value: 0x7f060000
			public const int newCharButton = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int newCharName = 2131099667;
			
			// aapt resource value: 0x7f06004c
			public const int paladinBtn = 2131099724;
			
			// aapt resource value: 0x7f06001c
			public const int pickAlign = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int pickBack = 2131099678;
			
			// aapt resource value: 0x7f060018
			public const int pickRace = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int pickSub = 2131099674;
			
			// aapt resource value: 0x7f06000e
			public const int playerModeBtn = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int playerName = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int race = 2131099656;
			
			// aapt resource value: 0x7f060041
			public const int raceLabel = 2131099713;
			
			// aapt resource value: 0x7f060016
			public const int radioFemale = 2131099670;
			
			// aapt resource value: 0x7f060011
			public const int radioGender = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int radioMale = 2131099669;
			
			// aapt resource value: 0x7f06004d
			public const int rangerBtn = 2131099725;
			
			// aapt resource value: 0x7f060002
			public const int relativeLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060042
			public const int remPoints = 2131099714;
			
			// aapt resource value: 0x7f06004e
			public const int rogueBtn = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int sorcerorBtn = 2131099727;
			
			// aapt resource value: 0x7f060025
			public const int strMinus = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int strPlus = 2131099687;
			
			// aapt resource value: 0x7f060024
			public const int strScore = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int strScoreNum = 2131099686;
			
			// aapt resource value: 0x7f060009
			public const int subRace = 2131099657;
			
			// aapt resource value: 0x7f060050
			public const int warlockBtn = 2131099728;
			
			// aapt resource value: 0x7f060039
			public const int wisMinus = 2131099705;
			
			// aapt resource value: 0x7f06003b
			public const int wisPlus = 2131099707;
			
			// aapt resource value: 0x7f060038
			public const int wisScore = 2131099704;
			
			// aapt resource value: 0x7f06003a
			public const int wisScoreNum = 2131099706;
			
			// aapt resource value: 0x7f060051
			public const int wizardBtn = 2131099729;
			
			// aapt resource value: 0x7f06000b
			public const int xp = 2131099659;
			
			// aapt resource value: 0x7f060054
			public const int yourClass = 2131099732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CharacterSelect = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CharacterSheet = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DmScreenBase = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DNDMain = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int newChar1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int newChar2 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int newChar3 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int newChar4 = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int alignment = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BackgroundList = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ClassList = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dwarfSub = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int elfSub = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int gnomeSub = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int halflingSub = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int RaceList = 2130968583;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
