#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GoSteve.Resource", IsApplication=true)]

namespace GoSteve
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int alignment = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int button1 = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int charBG = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int characterName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int classSelect = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int dmModeBtn = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int item0 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int item1 = 2131099662;
			
			// aapt resource value: 0x7f060017
			public const int item10 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int item11 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int item12 = 2131099673;
			
			// aapt resource value: 0x7f06000f
			public const int item2 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int item3 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int item4 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int item5 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int item6 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int item7 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int item8 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int item9 = 2131099670;
			
			// aapt resource value: 0x7f060003
			public const int level = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int playerModeBtn = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int playerName = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int race = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int subRace = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int xp = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CharacterSheet = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DmScreenBase = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DNDMain = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int alignment = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BackgroundList = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ClassList = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dwarfSub = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int elfSub = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int gnomeSub = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int halflingSub = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int RaceList = 2130968583;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
